name: TRLC PyPI Packages

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:

  package:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel requests
      - name:
        run: |
          make package
      - name: Archive wheel files
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: "dist/trlc-*.whl"

  upload-test:
    name: PyPI Upload
    needs: package
    runs-on: ubuntu-20.04
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Download wheel files
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: dist
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
