name: TRLC PyPI Packages

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:

  package:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel requests
      - name:
        run: |
          make package
      - name: Archive wheel files
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: "dist/trlc-*.whl"
