name: TRLC Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cvc5 pyvcg coverage
      - name: Executing system tests
        run: |
          make system-tests
      - name: Executing unit tests
        run: |
          make unit-tests
      - name: Coverage analysis
        run: |
          make coverage -o system-tests -o unit-tests
      - name: Test status
        run: |
          util/check_local_modifications.sh
